### ISSUE TITLE
Does tracker use LR1110 modem?

### ISSUE THREAD

**Issue by enddls** [Lora-net/lora_edge_tracker_ref_design#1]
hi

I research Lr1110. 

so I try to reference this code.

but my board "Lr1110" do not include lr1110-modem. so do you know how to use LR1110-modem?

what should i do if My Lr1110 can't use lr1110-modem.

should I refer to LRMAC-periodic-uplink-lpp?

if I programing LRMAC-periodic-uplink-lpp with gnss-scan, wifi-scan, lr1110 join the sever,whenever Lr1110 scan wifi, gnss?

**Comment by smtcbboulet** [comment]
Hello,
Yes the tracker uses the LR11110 Modem-E.
which board have you got ? 
to convert your LR1110 transceiver in a modem please uses this project : https://github.com/Lora-net/lr1110_updater_tool
your LR1110 can be a Modem, there is no problem here, 
once in modem you can use these projects : 
https://github.com/Lora-net/lora_edge_tracker_ref_design
https://github.com/Lora-net/lr1110_evk_demo_app
https://github.com/Lora-net/lr1110_modem_application_example

Regards,

Benjamin

**Comment by matthieuantoine** [comment]
Concerning the updater tool, there are pre-compiled binaries compatible with the combo [STM32L476RG nucleo + LR1110 shield] - [see here](https://github.com/Lora-net/lr1110_updater_tool/wiki#update-to-modem).

There is also a terminal-like interface program (binary file only) that can be used with a LoRa Basics Modem-E (aka LR1110 Modem-E) - [see here](https://github.com/Lora-net/lr1110_evk_demo_app/wiki/Command-tool-presentation).

**Comment by enddls** [comment]
> Hello,
> Yes the tracker uses the LR11110 Modem-E.
> which board have you got ?
> to convert your LR1110 transceiver in a modem please uses this project : https://github.com/Lora-net/lr1110_updater_tool
> your LR1110 can be a Modem, there is no problem here,
> once in modem you can use these projects :
> https://github.com/Lora-net/lora_edge_tracker_ref_design
> https://github.com/Lora-net/lr1110_evk_demo_app
> https://github.com/Lora-net/lr1110_modem_application_example
> 
> Regards,
> 
> Benjamin

hi smtcbboulet

I have my board that use lr1110, stm32l452.

my lr1110 doesn't use lr1110 modem.

if I don't use lr1110 modem, should lr1110 join the sever,whenever Lr1110 scan wifi, gnss?

**Comment by smtcbboulet** [comment]
Hello,

So you have your own board right ?
if you won't use the modem, the LR1110 can obviously join a Server and does Wi-Fi and GNSS scan .

Please take a look on this project which can use the LR1110 in transceiver mode as yours : https://github.com/Lora-net/lr1110_evk_demo_app
and the driver :  https://github.com/Lora-net/lr1110_driver 

regards,

Benjamin

**Comment by enddls** [comment]
> Hello,
> 
> So you have your own board right ?
> if you won't use the modem, the LR1110 can obviously join a Server and does Wi-Fi and GNSS scan .
> 
> Please take a look on this project which can use the LR1110 in transceiver mode as yours : https://github.com/Lora-net/lr1110_evk_demo_app
> and the driver : https://github.com/Lora-net/lr1110_driver
> 
> regards,
> 
> Benjamin


hi, smtcbboulet.

yes. I have a my own board.

lr1110_evk_demo_app is Lr1110 operation that when Lr1110 wasn't joined sever, lr1110 does scan Wifi and Gnss.

while LR1110 was joined a Server, Can Lr1110 does Wi-Fi and GNSS scan?

I want to lr1110 process 

1. lr1110 join sever.
2. lr1110 scan wifi and gnss.
3. lr1110 send scan data to sever.

but I programed that lr1110 should join server whenever lr1110 scan wifi and gnss, .

how does lr1110 scan wifi and gnss while lr1110 is joined sever?
