### ISSUE TITLE
App failed to work... (or maybe false upload procedure)

### ISSUE THREAD

**Issue by WisangAnggoro** [Lora-net/lora_edge_tracker_ref_design#10]
Hi there, I have issue with the uploading procedure. Here is what I already tried:
1. Uploading the OTA_BLE.bin from the bin folder on memory 0x08000000 via STM32CubeProg
2. Make tracker project using GCC and get tracker.bin on gcc/build folder
3. Uploading the gcc/build/tracker.bin memory 0x08007000 via STM32CubeProg
4. Disconnect from STM32CubeProg

with the procedures above, I got nothing from the serial interface. I also already uploaded hex from the hex_merged folder and no problem. UART work on 921600 baud rate and no problems at all. Am I doing it wrong? Any help/insight about upload procedure will be great. Thx 🙏🙏🙏

**Comment by smtcbboulet** [comment]
Hello,

I've build the .bin with GCC then flash with the following line :
./STM32_Programmer_CLI.exe -c port=SWD -w "PATH\LoRa-Net\lora_edge_tracker_ref_design\gcc\build\tracker.bin" 0x08007000

and it works, could you try it using the STM32CubeProg CLI instead of the GUI please ?

**Comment by WisangAnggoro** [comment]
Work like a charm 😸. In my case, I need to add under reset mode and software reset to make it work. This is the command I use if someone has the same issue:
`./STM32_Programmer_CLI.exe -c port=SWD mode=UR reset=SWrst -w "PATH\lora_edge_tracker_ref_design\gcc\build\wifi.bin" 0x08007000`
Idk what's wrong with my SMT32CubeProg GUI, but I just realize it has warned "address out of range" before it successfully uploads the bin. Anyway, @smtcbboulet thanks for your help and fast reply, helps me really well. I think I can close this issue...
