### ISSUE TITLE
How to execute Make -j in windows?

### ISSUE THREAD

**Issue by neosen-angus** [Lora-net/lora_edge_tracker_ref_design#4]
Do I need to install something else like mingw or visual studio?

Thanks

**Comment by smtcbboulet** [comment]
Hello, 

you also need the GNU Arm Embedded Toolchain (https://developer.arm.com/tools-and-software/open-source-software/developer-tools/gnu-toolchain/gnu-rm/downloads)

regards,

Ben

**Comment by neosen-angus** [comment]
> Hello,
> 
> you also need the GNU Arm Embedded Toolchain (https://developer.arm.com/tools-and-software/open-source-software/developer-tools/gnu-toolchain/gnu-rm/downloads)
> 
> regards,
> 
> Ben

Can I Just use Keil to compile the program?

**Comment by smtcbboulet** [comment]
if you have a license yes of course !

**Comment by neosen-angus** [comment]
> if you have a license yes of course !

Thanks I got it now. The make command exists just because the compile size exceeds the limit of the Keil free version.
