### ISSUE TITLE
upgrade the BLE stack firmware: error in user guide

### ISSUE THREAD

**Issue by tantudaisu** [Lora-net/lora_edge_tracker_ref_design#7]
There is an error in LoRa Edge™Tracker Reference Design User Guide.pdf (release: October 2020) related to BLE stack firmware upgrade. 

**Section: 4.1.2.3** How to Flash M0+ Dedicated to BLE **step 4) c)**

Command to install the stack firmware, has an error in adress:
STM32_Programmer_CLI.exe -c port=usb1 -fwupgrade stm32wb5x_BLE_Stack_full_fw.bin 0x080**CB**000 firstinstall=1

According ST documentation:  Provides Install address for the targeted binary to be  0x080**CA**000

![image](https://user-images.githubusercontent.com/86839933/125452556-552d842b-de7c-41be-9e28-cdfc14d87084.png)

**Comment by smtcbboulet** [comment]
Hello,

according to STM32Cube_FW_WB_V1.8.0.

![image](https://user-images.githubusercontent.com/61151331/125457225-b4b61015-d944-4946-870e-43ecd75234d8.png)

STM32_Programmer_CLI.exe -c port=usb1 -fwupgrade stm32wb5x_BLE_Stack_full_fw.bin 0x080CB000 firstinstall=1.

which version are you using of CUBE_WB ?

thanks,

Benjamin

**Comment by tantudaisu** [comment]
I have tryed to flash the most recent STM32Cube_FW_WB_V1.11.0 

Should i use STM32Cube_FW_WB_V1.8.0 on development kit?

**Comment by smtcbboulet** [comment]
I guess it works with STM32Cube_FW_WB_V1.11.0 but I didn't tried it. I will do
